### ISSUE TITLE
cv2.error 

### ISSUE THREAD

**Issue by Klonslyersdeath** [noahcoolboy/toucan-track#4]
im prety new to doing things like this so i must admit that i might be dump but i got this error while runing calib.py:
  File "C:\Users\mauri\toucan-track\calib.py", line 518, in <module>
    cmtx0, dist0 = calibrate_camera_for_intrinsic_parameters(images_prefix)
  File "C:\Users\mauri\toucan-track\calib.py", line 135, in calibrate_camera_for_intrinsic_parameters
    ret, cmtx, dist, rvecs, tvecs = cv.calibrateCamera(objpoints, imgpoints, (width, height), None, None)
cv2.error: OpenCV(4.7.0) D:\a\opencv-python\opencv-python\opencv\modules\calib3d\src\calibration.cpp:3749: error: (-215:Assertion failed) nimages > 0 in function 'cv::calibrateCameraRO

what can i do to fix this?

**Comment by noahcoolboy** [comment]
Hello! This error happens when the checkerboard pattern is not detected on any of the calibration frames.
Here's some options you can try:
- Configure checkerboard_columns and checlerboard_rows to the correct size of your calibration pattern. Remember it's the corners which get counted and not the amount of squares.
- Make sure the camera can see the full calibration board! Occlusion is not allowed
- Don't get too far from the camera. If the board is too small or far away, it won't be detected! You can try getting a bigger calibration board.

Please do tell me if these solutions have helped you getting ToucanTrack to work.
Thanks!

**Comment by Klonslyersdeath** [comment]
thy for the answer it sadly seems that my room is to dark to use toucan-trank and i cant change my lighting situation
